name: R quality
{% set effective_formatter = quality_tools.formatter if quality_tools.formatter in template_supported_choices.quality_tools.formatter else "" %}
{% set effective_linter = quality_tools.linter if quality_tools.linter in template_supported_choices.quality_tools.linter else "" %}

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ '{{' }} github.workflow {{ '}}' }}-${{ '{{' }} github.ref {{ '}}' }}
  cancel-in-progress: true

jobs:
  quality:
    name: Check R source quality
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      LINTR_ERROR_ON_LINT: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
      - uses: r-lib/actions/setup-r-dependencies@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          needs: check
{% if effective_formatter == "styler" %}      - name: Check formatting
        shell: Rscript {0}
        run: styler::style_pkg(dry = "fail")
{% endif %}{% if effective_linter == "lintr" %}      - name: Lint package
        shell: Rscript {0}
        run: lintr::lint_package()
{% endif %}
