name: License Compatibility

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ '{{' }} github.workflow {{ '}}' }}-${{ '{{' }} github.ref {{ '}}' }}
  cancel-in-progress: true

jobs:
  license-compatibility:
    name: Check dependency licenses
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/setup-python-project
      - name: Check dependency license compatibility
        run: @@PROJECT_RUN@@licensecheck
